<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyTitle>PrintHero</AssemblyTitle>
		<AssemblyDescription>Automatic PDF printing service</AssemblyDescription>
		<ApplicationIcon>Resources\PrintHero.ico</ApplicationIcon>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PreserveCompilationContext>true</PreserveCompilationContext>
		<PublishSingleFile>false</PublishSingleFile>
		<SelfContained>false</SelfContained>
	</PropertyGroup>


	<ItemGroup>
	  <None Remove="Resources\printhero-logo.png" />
	  <None Remove="Resources\PrintHero.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.6" />
		<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
		<PackageReference Include="System.Management" Version="6.0.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PrintHero.Core\PrintHero.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\printhero-logo.png">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\PrintHero.ico">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>
